config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :bugs
    resources :tags
  end
  resource :session
  resources :passwords, param: :token

  resources :users, only: [ :new, :create, :show, :edit, :update ]

  mount ActiveStorageDashboard::Engine, at: "/active-storage-dashboard"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "projects#index"
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :memberships, dependent: :destroy
  has_many :members, through: :memberships, class_name: "User"
  has_many :bugs, dependent: :destroy
  has_many :tags, dependent: :destroy

  after_create_commit :create_default_tags

  def owner
    memberships.find_by(role: "owner")&.member
  end

  def create_default_tags
    Constants::DEFAULT_TAGS.each do |tag_params|
      tag = Tag.new(tag_params)
      tag.project_id = self.id
      tag.save!
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show ]
  before_action :verify_user, only: %i[ edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)
    @membership = Membership.new(project: @project, member: Current.user, role: "owner")

    begin
      ActiveRecord::Base.transaction do
        @project.save!
        @membership.save!
      end

      respond_to do |format|
        format.html { redirect_to @project, notice: "Project was successfully created." }
      end

    rescue ActiveRecord::RecordInvalid
      respond_to do |format|
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy!

    respond_to do |format|
      format.html { redirect_to projects_path, status: :see_other, notice: "Project was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.expect(project: [ :title, :description ])
    end

    def verify_user
      set_project
      redirect_to root_path, alert: "NO, BAD." and return if Current.user != @project.owner && !Current.user.admin
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <div id="project_form">
      <h2><%= action %></h2>
      <% if project.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

          <ul>
            <% project.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

    <div>
      <%= form.label :title, style: "display: block" %>
      <%= form.text_field :title, required: true %>
    </div>

    <div>
      <%= form.label :description, style: "display: block" %>
      <%= form.text_area :description, required: true, size: "50x5" %>
    </div>

    <div>
      <%= form.submit %>
    </div>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <h2><%=link_to project.title, project_path(project) %></h2>

  <p>
    <%= project.description %>
  </p>

  <p>
    <strong>Owner:</strong>
    <%= project.owner.username %>
  </p>

  <% if project.owner == Current.user || Current.user.admin %>
    <%= link_to "Edit this project", edit_project_path(project) %>
    <%= button_to "Destroy this project", project, method: :delete %> 
  <% end %>
</div>

app/views/projects/_projects.html.erb
<div id="projects">
    <% @projects.each do |project| %>
        <%= render project, project: project %>
    <% end %>
</div>

app/views/projects/edit.html.erb
<div id="page_content">
    <% content_for :title, "Editing project" %>

    <h1><%= link_to @project.title, @project %></h1>

    <%= render "form", project: @project, action: "Edit Project" %>

    <br>

    <div id="bubble">
        <%= render "tags/tags_editable", tags: @project.tags %>
        <%= render "tags/new_button", tag: Tag.new, project: @project, action: "Create" %>
    </div>
</div>

app/views/projects/index.html.erb
<div id="left_bar">
  <h2>My Logged Bugs</h2>
  <div id="sidebar_bugs">
    <%= render Bug.where(author: Current.user).order(title: :desc), project: @project, type: "sidebar" %>
  </div>
</div>

<div id="page_content">
  <% flash.each do |type, message| %>
    <p style="color: <%= type == "alert" ? "red" : "green" %>"><%= message %></p>
  <% end %>

  <% content_for :title, "Projects" %>

  <h1>Projects</h1>
  <%= render @projects %>
  <%= link_to "New project", new_project_path %>
</div>

app/views/projects/new.html.erb
<div id="page_content">
    <% content_for :title, "New project" %>

    <%= render "form", project: @project, action: "New Project" %>

    <br>

    <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/show.html.erb
<%# TODO THIS NEEDS TO GO SOMEWHERE ELSE %>
<div id="left_bar">
  <h2>My Logged Bugs</h2>
  <div id="sidebar_bugs">
    <%= render @project.bugs.where(author: Current.user).order(title: :desc), project: @project, type: "sidebar" %>
  </div>
</div>

<div id="page_content">
  <p style="color: green"><%= notice %></p>
  <h1>Project Information</h1>
  <%= render @project %>
  <h1>Bugs</h1>
  <%= render "bugs/new_button", project: @project, bug: Bug.new %>
  <br>
  <br>

  <%= turbo_stream_from "project_bugs_sub_#{@project.id}" %>
  <div id="bugs">
    <%= render @project.bugs.order(created_at: :desc), project: @project, type: "main" %>
  </div>
</div>

<div id="right_bar">
  <h2>Project Tags</h2>
  <div id="sidebar_tags">
    <%= render @project.tags.order(weight: :desc) %>
  </div>
</div>