config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :bugs
    resources :tags
  end
  resource :session
  resources :passwords, param: :token

  resources :users, only: [ :new, :create, :show, :edit, :update ]

  mount ActiveStorageDashboard::Engine, at: "/active-storage-dashboard"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "projects#index"
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :project
  has_many :bug_tags, dependent: :destroy
  has_many :bugs, through: :bug_tags
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :verify_user, only: %i[ destroy edit update ]
  def new
    @tag = Tag.new
    @project = Project.find(params[:project_id])
  end

  def create
    @project = Project.find(params[:project_id])
    @tag = @project.tags.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.turbo_stream
        format.html { redirect_to @project, notice: "Tag was successfully created." }
      else
        flash.now[:alert] = "Failed to create tag"
        render "projects/edit", status: :unprocessable_entity
      end
    end
  end

  def edit
  end

  def update
    if @tag.update(tag_params)
      respond_to do |format|
        format.turbo_stream
      end
    else
      render "projects/show", status: :unprocessable_entity
    end
  end

  def destroy
    @tag.destroy!
    respond_to do |format|
      format.html { redirect_to edit_project_path, status: :see_other, notice: "Tag was successfully destroyed." }
    end
  end

  private
  def tag_params
    params.expect(tag: [ :name, :weight ])
  end

  def set_project_and_tag
    @tag = Tag.find(params[:id])
    @project = @tag.project
  end

  def verify_user
    set_project_and_tag
    redirect_to root_path, alert: "NO, BAD." and return if Current.user != @project.owner && !Current.user.admin
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_edit_button.html.erb
<%= turbo_frame_tag combined_dom_id(project, tag) do %>
    <%= link_to "Edit tag", edit_project_tag_path(project, tag) %>
<% end %>

app/views/tags/_form.html.erb
<%= turbo_frame_tag combined_dom_id(project, tag) do %>
    <div id="bubble">
    <h2><%= action %></h2>
    <%= form_with model: [project, tag] do |form| %>
        <div>
            <%= form.label :name %>
            <%= form.text_field :name, required: true %>
        </div>
        <div>
            <%= form.label :weight %>
            <%= form.number_field :weight, in: 0..5, step: 0.1 %>
        </div>
        <div>
            <%= form.submit %>
        </div>
    <% end %>

    <%= link_to "Cancel", edit_project_path(project) %>
</div>
<% end %>

app/views/tags/_new_button.html.erb
<%= turbo_frame_tag combined_dom_id(project, tag) do %>
    <%= link_to "New Tag", new_project_tag_path(project, tag) %>
<% end %>

app/views/tags/_tag.html.erb
<div id=<%= dom_id(tag) %>>
    <span><%= tag.name %> (<%= tag.weight %>)</span>
</div>

app/views/tags/_tag_editable.html.erb
<div id="<%= dom_id(tag, :edit) %>" style="display: flex;">
    <p><%= tag.name %></p>

    <div style="margin-left: auto; display: flex; gap: 1em">
        <p>Weight: <%= tag.weight %></p>
        <%= render "tags/edit_button", tag: tag, project: tag.project %>
        <%= button_to "Delete", project_tag_path(tag.project, tag), method: :delete %>
    </div>
</div>

app/views/tags/_tags_editable.html.erb
<div id="tags_editable">
    <% for tag in tags %>
        <%= render "tags/tag_editable", tag: tag %>
    <% end %>
</div>

app/views/tags/create.turbo_stream.erb
<%= turbo_stream.replace "tags_editable" do %>
    <%= render "tags/tags_editable", tags: @project.tags %>
<% end %>

<%= turbo_stream.replace combined_dom_id(@project, Tag.new) do %>
    <%= render "tags/new_button", tag: Tag.new, project: @project, action: "Create" %>
<% end %>

app/views/tags/edit.html.erb
<div id="page_content">
    <%= render "tags/form", project: @project, tag: @tag, action: "Edit Tag" %>
</div>

app/views/tags/new.html.erb
<%= render "tags/form", project: @project, tag: @tag, action: "New" %>

app/views/tags/update.turbo_stream.erb
<%= turbo_stream.replace dom_id(@tag, :edit) do %>
    <%= render "tags/tag_editable", tag: @tag %>
<% end %>