config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :bugs
    resources :tags
  end
  resource :session
  resources :passwords, param: :token

  resources :users, only: [ :new, :create, :show, :edit, :update ]

  mount ActiveStorageDashboard::Engine, at: "/active-storage-dashboard"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "projects#index"
end

app/models/bug.rb
class Bug < ApplicationRecord
  belongs_to :author, class_name: "User"
  belongs_to :project
  has_rich_text :description
  has_many :bug_tags, dependent: :destroy
  has_many :tags, through: :bug_tags, dependent: :destroy

  after_create_commit -> { broadcast_prepend_to "project_bugs_sub_#{self.project.id}", partial: "bugs/bug", locals: { bug: self, project: self.project, type: "main" }, target: "bugs" }
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  before_action :verify_user, only: %i[destroy edit update]
  def new
    @bug = Bug.new
    @project = Project.find(params[:project_id])
  end

  def edit
    @bug = Bug.find(params[:id])
    @project = @bug.project
  end

  def update
    @bug = Bug.find(params[:id])
    filtered_params = bug_params

    if @bug.update(filtered_params)
      @bug.bug_tags.where.not(tag_id: filtered_params[:tag_ids]).destroy_all
      respond_to do |format|
        format.turbo_stream
      end
    else
      render "projects/show", status: :unprocessable_entity
    end
  end

  def create
    @project = Project.find(params[:project_id])
    @bug = Bug.new
    @bug = @project.bugs.new(bug_params)
    @bug.author = Current.user


    respond_to do |format|
      if @bug.save
        format.turbo_stream
        format.html { redirect_to @project, notice: "Bug was successfully created." }
      else
        flash.now[:alert] = "Failed to create bug"
        format.html { render "projects/show", status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @bug.destroy!

    respond_to do |format|
      format.html { redirect_to project_path(@bug.project), status: :see_other, notice: "Bug was successfully destroyed." }
    end
  end

  private
  def set_bug
    @bug = Bug.find(params[:id])
  end

  def verify_user
    set_bug
    redirect_to root_path, alert: "NO, BAD. You can't edit other user's bugs" and return if Current.user != @bug.author && Current.user != @bug.project.owner && !Current.user.admin
  end

  def bug_params
    final_params = params.expect bug: [ :title, :description, :completed, tag_ids: [] ]
    if final_params.has_value?(:tag_ids)
      final_params[:tag_ids] = final_params[:tag_ids].reject { |tag_id| tag_id.blank? || @bug.bug_tags.exists?(tag_id) } if @bug.tags.any?
    end
    final_params
  end
end

app/helpers/bugs_helper.rb
module BugsHelper
  def get_bug_score(bug)
    bug.tags.map { |tag| tag.weight }.reduce(1.0) { |score, weight| weight * score }.floor
  end
end

app/views/bugs/_bug.html.erb
<% if type == "sidebar" %>
    <div id="<%= dom_id(bug, :sidebar) %>">
        <p><%= link_to "#{bug.title}: #{"in" unless bug.completed }complete", project_path(bug.project, anchor: dom_id(bug)) %></p>
    </div>
<% else %>
    <div id="<%= dom_id(bug) %>">
        <%= render "bugs/content", bug: bug %>
        <% if Current.user == project.owner || Current.user.admin || Current.user == bug.author %>
            <%= button_to "Destroy bug", project_bug_path(project, bug), method: :delete %>
            <%= render "bugs/form_toggle_completion", project: project, bug: bug %>
            <%= render "bugs/edit_button", project: project, bug: bug %>
        <% end %>
    </div>
<% end %>

app/views/bugs/_content.html.erb
<div id="<%= dom_id(bug, :content) %>" > 
    <h2><%= bug.title %></h2>
    <h3><%= "COMPLETED" if bug.completed %></h3>
    <p><%= bug.description %></p>
    <hr>
    <br>
    <% if bug.tags.any? %>
        <%= render bug.tags %>
        <span type="score">Bug Score: <%= get_bug_score bug %></span>
    <% end %>
    <p style="font-size: 14px;"><b>Author: </b><%= bug.author.username %> | 
        <b>Created</b>: <%= bug.created_at.in_time_zone(Current.user.time_zone) %>
    </p>
</div>

app/views/bugs/_edit_button.html.erb
<%= turbo_frame_tag combined_dom_id(project, bug) do %>
    <%= link_to "Edit Bug", edit_project_bug_path(project, bug) %>
<% end %>

app/views/bugs/_form.html.erb
<%= turbo_frame_tag combined_dom_id(project, bug) do %>
    <div id="bubble">
        <h2><%= action %></h2>
        <%= form_with model: [project, bug] do |form| %>
            <div>
                <%= form.label :title %>
                <%= form.text_field :title, required: true %>
            </div>
            <div>
                <%= form.label :description %>
                <%= form.rich_text_area :description %>
            </div>

            <div>
                <%= form.label :tag_ids, "Tags" %><br>
                <%= form.collection_check_boxes :tag_ids, project.tags, :id, :name %>
            </div>

            <div>
                <%= form.submit %>
            </div>
        <% end %>
        <%= link_to "Cancel", project_path(project) %>
    </div>
<% end %>

app/views/bugs/_form_toggle_completion.html.erb
<%= turbo_frame_tag "completion_#{combined_dom_id(project, bug)}" do %>
    <%= form_with model: [project, bug] do |form| %>
        <div>
            <%= form.hidden_field :completed, value: !bug.completed %>
        </div>
        <div>
            <%= form.submit "Mark #{"in" if bug.completed}complete" %>
        </div>
    <% end %>
<% end %>

app/views/bugs/_new_button.html.erb
<%= turbo_frame_tag combined_dom_id(project, bug) do %>
    <%= link_to "New Bug", new_project_bug_path(project, bug) %>
<% end %>

app/views/bugs/create.turbo_stream.erb
<%= turbo_stream.prepend "bugs" do %>
    <%= render "bugs/bug", bug: @bug, project: @project, type: "main" %>
<% end %>

<%= turbo_stream.replace combined_dom_id(@project, Bug.new) do %>
    <%= render "bugs/new_button", bug: Bug.new, project: @project %>
<% end %>

app/views/bugs/edit.html.erb
<%= render "bugs/form", bug: @bug, project: @project, action: "Edit Bug"%>

app/views/bugs/new.html.erb
<%= render "bugs/form", bug: @bug, project: @project, action: "New Bug" %>

app/views/bugs/update.turbo_stream.erb
<%= turbo_stream.replace dom_id(@bug, :content), partial: "bugs/content", locals: { bug: @bug } %>
<%= turbo_stream.replace combined_dom_id(@bug.project, @bug), partial: "bugs/edit_button", locals: { bug: @bug, project: @bug.project } %>
<%= turbo_stream.replace "completion_#{combined_dom_id(@bug.project, @bug)}", partial: "bugs/form_toggle_completion", locals: { bug: @bug, project: @bug.project } %>