config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :bugs
    resources :tags
  end
  resource :session
  resources :passwords, param: :token

  resources :users, only: [ :new, :create, :show, :edit, :update ]

  mount ActiveStorageDashboard::Engine, at: "/active-storage-dashboard"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "projects#index"
end

app/views/layouts/_nav.html.erb
<nav class="menu">
  <% if !authenticated? %>
    <%= link_to "Register", new_user_path %>
    <%= link_to "Login", new_session_path %>
  <% else %>
  <%= link_to "Home", root_path %>
    <%= button_to "Logout", session_path, method: :delete %>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Phasmid" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <%= favicon_link_tag 'favicon.ico' %>
    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
  </head>

  <body>
    <div id="base">
      <%= render "layouts/nav" %>
      <div id="container">
        <%= yield %>
      </div>
    </div>
  </body>
</html>